CREATE TABLE edge_tifs (
   CompanyName              VARCHAR(4000),
   Address                  VARCHAR(4000),
   City                     VARCHAR(4000),
   County                   VARCHAR(4000),
   State                    VARCHAR(4000),
   ZIP_Code                 INTEGER,
   Latitude                 DOUBLE PRECISION,
   Longitude                DOUBLE PRECISION,
   TIFAmount                INTEGER,
   TotalInvestment          INTEGER,
   ProjectedMWBESpending    INTEGER,
   ProjectedTotalJobs       INTEGER,
   Approved_Date            DATE
);

CREATE TABLE edge_bonds(
   CompanyName              VARCHAR(4000),
    Address                  VARCHAR(4000),
    City                     VARCHAR(4000),
   STATE                    VARCHAR(4000),
   ZIP_Code                 INTEGER,
    Latitude                 DOUBLE PRECISION,
    Longitude                DOUBLE PRECISION,
    BondAmount               INTEGER,
   TotalInvestment          INTEGER,
   ProjectedTotalJobs       INTEGER,
    Approved_Date            DATE
);

CREATE TABLE edge_pilots (
    CompanyName                              VARCHAR(4000),
    CityCouncilDistrict                      INTEGER,
    CountyCommissionDistrict                 INTEGER,
    ProjectType                              VARCHAR(4000),
    PilotType                                VARCHAR(50),
    PilotStatus                              VARCHAR(50),
    PilotTerm                                NUMERIC(5,2),
    ProjectedTaxesAbatedCity                 NUMERIC(12,2),
    ProjectedTaxesAbatedCounty               NUMERIC(12,2),
    Approved_Date                            DATE,
    RampUpPeriod                             INTEGER,
    ProjectedNewJobs                         INTEGER,
    ProjectedAveragePayrollOfNewJobs         NUMERIC(12,2),
    TotalNewPayroll                          NUMERIC(14,2),
    ProjectedRetainedJobs                    INTEGER,
    ProjectedAveragePayrollOfRetainedJobs    NUMERIC(12,2),
    TotalRetainedPayroll                     NUMERIC(16,2),
    TotalJobs                                INTEGER,
    EmploymentDirect                         INTEGER,
    EmploymentIndirect                       INTEGER,
    WagesDirect                              NUMERIC(14,2),
    WagesIndirect                            NUMERIC(14,2),
    ProjectedCapitalInvestment               NUMERIC(16,2),
    RealPropertyInvestment                   NUMERIC(16,2),
    PersonalPropertyInvestment               NUMERIC(16,2),
    CommunityReinvestmentCredit              NUMERIC(16,2),
    CapitalInvestmentNotInPilot              NUMERIC(16,2),
    ProjectedMWBE_LOSBSpending               NUMERIC(16,2),
    MWBE_LOSBSpendingConstruction            NUMERIC(16,2),
    MWBE_LOSBSpendingOperations              NUMERIC(16,2),   -- ← FIXED POSITION
    TotalCapitalInvestment                   NUMERIC(16,2),
    TotalIncentiveProvided                   NUMERIC(16,2),
    TotalNewTaxRevenues                      NUMERIC(16,2),
    BenefitCostRatio                         NUMERIC(16,4),
    Latitude                                 DOUBLE PRECISION,
    Longitude                                DOUBLE PRECISION,
    Main_Address                             VARCHAR(255),
    City                                     VARCHAR(50),
    State                                    VARCHAR(2),
    ZIP_Code                                 VARCHAR(10)
);


CREATE TABLE edge_loans(
CompanyName                        VARCHAR(4000),
ProjectType                        VARCHAR(255),
LoanType                           VARCHAR(255),
Address                            VARCHAR(255),
City                               VARCHAR(100),
State                              VARCHAR(2),
ZIP_Code                           VARCHAR(10),
Latitude                           DOUBLE PRECISION,
Longitude                          DOUBLE PRECISION,
CityCouncilDistrict                INTEGER,
CityCouncilSuperDistrict           INTEGER,
CountyCommissionDistrict           INTEGER,
Term                               INTEGER,
ProjectedNewJobs                   INTEGER,
ProjectedRetainedJobs              INTEGER,
AveragePayroll                     NUMERIC(14,2),
Approved_Date                      DATE,
LoanAmount                         NUMERIC(16,2),
LoanUse                            VARCHAR(4000),
InterestRate                       NUMERIC(6,4),
TotalProjectedCapitalInvestment    NUMERIC(16,2),
PCI_RealProperty                   NUMERIC(16,2),
PCI_Acquisition                    NUMERIC(16,2),
PCI_Construction                   NUMERIC(16,2),
PCI_Renovation                     NUMERIC(16,2),
PCI_MachineryEquipment             NUMERIC(16,2),
PCI_FurnitureFixturesOffice        NUMERIC(16,2),
PCI_Equipment                      NUMERIC(16,2),
PCI_FeesSoftCosts                  NUMERIC(16,2),
PCI_PermanentWorkingCapital        NUMERIC(16,2),
PCI_Miscellaneous                  NUMERIC(16,2)
);


CREATE TABLE edge_OtherProjects(
CompanyName            VARCHAR(4000),
OtherType              VARCHAR(255),
Approved_Date          DATE,
Address                VARCHAR(255),
City                   VARCHAR(100),
County                 VARCHAR(100),
State                  VARCHAR(2),
ZIP_Code               VARCHAR(10),
Latitude               DOUBLE PRECISION,
Longitude              DOUBLE PRECISION,
FinancingAmount        NUMERIC(16,2),
TotalInvestment        NUMERIC(16,2),
ProjectedTotalJobs     INTEGER
)
;
